title: Page simple
tabs:
  content:
    columns:
      - width: 2/3
        sections:
          blockContent:
            type: fields
            fields:
              blockContent: fields/blockContent
      - width: 1/3
        sections:
          hero:
            type: fields
            fields:
              hero: fields/hero
  medias:
    sections:
      files: true