title: page.title
columns:
  - width: 2/3
    sections:
      actualites: sections/actualites
  - width: 1/3 
    sections:
      content:
        type: fields
        fields:
          hero: fields/hero
