title: Default Page
fields:
  sections:
    label: Sections
    type: blocks
    fieldsets:
      - hero
      - content
      - about
      - contact
      - products
      - services
      - contact
      - makeup
      - workshops
