title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          sections:
            label: Sections
            type: blocks
            fieldsets:
              - hero
              - about
              - contact
              - products
              - services
              - contact
              - makeup
              - workshops
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

