# Each page blueprint must have a title, the title may be different from the file name
title: Projet

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 🖼

num: date
status:
  draft:
    label: Draft
    text: The note is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The note is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The note is online and listed in the blog

tabs:
  content:
    label: Contenu
    columns:
      - width: 2/3
        sections:
          article:
            type: fields
            fields:
              headline:
                label: Titre
                type: text
                default: "{{ page.title }}"
                maxlength: 64
                required: true
              subheadline:
                label: Description
                type: textarea
                maxlength: 200
                required: true
              article: fields/article
      - width: 1/3
        fields:
          cover: fields/cover
          date:
            type: date
            default: now
            display: DD/MM/YYYY
            required: true
          author:
            type: users
            required: true
          projectStatus:
            label: Statut du projet
            type: select
            default: En cours
            required: true
            options:
              Terminé: Terminé
              En cours: En cours
              En projet: Projet futur
          projectType:
            label: Type du projet
            type: multiselect
            default: autres
            required: true
            options:
              type: query
              query: site.find("projects").projectTypes.toStructure
              text: "{{ item.title }}"
              value: "{{ item.id }}"
          location:
            type: object
            fields:
              lat:
                label: Latitude
                type: number
                icon: map-marker
                required: true
              lon:
                label: Longitude
                type: number
                icon: map-marker
                required: true
