# Each page blueprint must have a title, the title may be different from the file name
title: Project

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 🖼

num: date
status:
  draft:
    label: Draft
    text: The note is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The note is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The note is online and listed in the blog


columns:
  
  - width: 2/3
     fields:
      text:
        type: blocks

  - width: 1/3

      fields:
        cover: fields/cover
        headline:
          label: Titre
          type: text
          default: "{{ page.title }}"
          help: Leave empty to use the title as headline
          maxlength: 64
        subheadline:
          label: Description
          type: textarea
          maxlength: 200
        date:
          type: date
          default: now
          display: DD/MM/YYYY
        author:
          type: users
        projectStatus:
          label: Statut du projet
          type: select
          default: inProgress
          options:
            Terminé: Terminé
            En cours: En cours
            En projet: Projet futur
        locationLat:
          label: Latitude
          type: number
          icon: map-marker
        locationLong:
          label: Longitude
          type: number
          icon: map-marker
        