name: Products
fields:
  title:
    label:
      fr: Titre
      en: Title
    type: text
  description:
    label: Description
    type: writer
  products:
    label:
      fr: Services
      en: Services
    type: structure
    fields:
      title:
        label:
          fr: Titre
          en: Title
        type: text
      description:
        label: Description
        type: writer
      price:
        label:
          fr: Prix
          en: Price
        type: text
        required: true
      product_image:
        label: Image
        type: files
        multiple: false
