name: Services
fields:
  title:
    label:
      fr: Titre
      en: Title
    type: text
  description:
    label: Description
    type: writer
  services:
    label:
      fr: Services
      en: Services
    type: structure
    fields:
      title:
        label:
          fr: Titre
          en: Title
        type: text
      description:
        label: Description
        type: writer
      service_image:
        label: Image
        type: files
        multiple: false
      prices:
        type: structure
        fields:
          title:
            required: true
            label:
              fr: Titre
              en: Title
            type: text
          description:
            label: Description
            type: writer
          price:
            label:
              fr: Prix
              en: Price
            type: text
            required: true
          duration:
            type: text



